import { useEffect, useState, useRef } from "react";
import axios from "axios";
import { useParams } from "react-router-dom";
import "../App.css";
import { toast } from "react-toastify";
import { useNavigate } from "react-router-dom";
import { jwtDecode } from "jwt-decode";
import { QRCodeCanvas } from "qrcode.react";
import jsPDF from "jspdf";
import CalendarView from "./CalendarView";


function TripDetailsPage() {
  const [shareLink, setShareLink] = useState("");
  const [shareAccess, setShareAccess] = useState("VIEW");

  const { id } = useParams();
  const { userId } = useParams();

  const [trip, setTrip] = useState(null);

  const [checklistItem, setChecklistItem] = useState("");
  const [checklist, setChecklist] = useState([]);

  const [budgetSummary, setBudgetSummary] = useState(null);

  const [showReminderInput, setShowReminderInput] = useState(false);

  const navigate = useNavigate();

  const createShareLink = async () => {
  try {
    const response =
      await axios.post(
        `https://localhost:7215/api/Share/create?tripId=${id}&accessType=${shareAccess}`
      );

    setShareLink(
      response.data.link
    );
    toast.success(
      "Share link created!"
    );
  } catch (error) {

    console.log(error);

    toast.error(
      "Failed to create share link."
    );
  }
};

const copyShareLink = async () => {
    try {
      await navigator.clipboard.writeText(
        shareLink
      );
      toast.success(
        "Link copied!"
      );

    } catch {
      toast.error(
        "Copy failed."
      );
    }
};


const generatePdf = () => {
  const doc = new jsPDF();

  doc.setFillColor(66, 165, 245);
  doc.rect(
    0,
    0,
    210,
    30,
    "F"
  );

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.text(
    trip.title,
    20,
    20
  );

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(18);

  doc.text(
    "Trip Overview",
    20,
    45
  );

  doc.setFontSize(13);

  doc.text(
    trip.description,
    20,
    55
  );

  doc.text(
    `Budget: ${trip.budget}`,
    20,
    70
  );

  doc.text(
    `Dates: ${
      trip.startDate.slice(0, 10)
    } - ${
      trip.endDate.slice(0, 10)
    }`,
    20,
    80
  );

  let y = 100;

  doc.setFontSize(18);
  doc.text(
    "Destinations",
    20,
    y
  );

  y += 12;

  trip.destinations.forEach((destination) => {
    doc.setFontSize(13);
    doc.text(
      destination.name,
      20,
      y
    );

    doc.text(
      destination.location,
      30,
      y + 6
    );

    y += 16;
  });


  y += 10;

  doc.setFontSize(18);
  doc.text(
    "Activities",
    20,
    y
  );

  y += 12;

  trip.activities.forEach((activity) => {
    doc.setFontSize(13);
    doc.text(
      `${activity.time} - ${activity.title}`,
      20,
      y
    );

    y += 10;
  });

  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text(
    "Generated by Travel Planner",
    20,
    280
  );

  doc.save(
    `${trip.title}.pdf`
  );
};


  const getTrip = async () => {
    try {
      const token = localStorage.getItem("token");

      const response = await axios.get(
        `https://localhost:7215/api/Trip/${id}`,
        {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        }
      );

      setTrip(response.data);
    } catch (error) {
      console.log(error);

      if(error.response?.status === 401){
        localStorage.removeItem("token");

        window.location.href = "/";
      }
    }
  };

  

    const deleteDestination = async (destinationId) => {
      const confirmed = window.confirm("Are you sure you want to delete this destination?");

      if (!confirmed) {
        return;
      }
      try {
        const token = localStorage.getItem("token");

        await axios.delete(
        `https://localhost:7215/api/Destination/${destinationId}`,
        {
          headers: {
          Authorization: `Bearer ${token}`,
          },
        }
      );

      getTrip();
      toast.success("Destination deleted!");
      } catch (error) {
        console.log(error);

        if (error.response?.status === 401) {
          localStorage.removeItem("token");

          window.location.href = "/";
        }
      }
  };

  const deleteActivity = async (activityId) => {
    const confirmed = window.confirm("Are you sure you want to delete this activity?");

      if (!confirmed) {
        return;
      }
      try {
        const token = localStorage.getItem("token");

        await axios.delete(
          `https://localhost:7215/api/Activity/${activityId}`,
          {
            headers: {
            Authorization: `Bearer ${token}`,
            },
          }
        );
        getTrip();
        toast.success("Activity deleted!");
      } catch (error) {
        console.log(error);

        if (error.response?.status === 401) {
          localStorage.removeItem("token");

          window.location.href = "/";
        }
    }
  };


const addChecklistItem = async () => {
      if (!checklistItem) {
        return;
      }
      const token = localStorage.getItem("token");
      await axios.post(
        "https://localhost:7215/api/Checklist",
        {
          text: checklistItem,
          tripId: id,
        },
        {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        }
      );
      setChecklistItem("");
      getChecklist();
    };

    const getChecklist = async () => {
      const token = localStorage.getItem("token");

      const response = await axios.get(
        `https://localhost:7215/api/Checklist/trip/${id}`,
      {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      }
    );
    setChecklist(response.data);
  };

const toggleChecklistItem = async (id) => {
  const token = localStorage.getItem("token");
  await axios.put(
    `https://localhost:7215/api/Checklist/${id}`,
    {},
    {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    }
  );
  getChecklist();
};

const getBudgetSummary = async () => {
  try {
    const spent = trip.activities.reduce((sum, activity) => 
      sum + activity.estimatedCost, 0);

    const response = await axios.get(
      `https://localhost:7286/api/Budget`,
      {
        params: {
          plannedBudget: trip.budget,
          spent
        }
      }
    );

    setBudgetSummary(response.data);
  } catch(error) {
    console.log(error);
  }
};


  useEffect(() => {
    getTrip();
    getChecklist();
  }, []);

  useEffect(() => {
      if(trip) {
      getBudgetSummary();
    }
  }, [trip]);
  
  if (!trip) {
    return <h1>Loading...</h1>;
  }

  const groupActivities = trip.activities.reduce(
  (groups, activity) => {
    const date = activity.date.slice(0,10);

    if(!groups[date]){
      groups[date] = [];
    }

    groups[date].push(activity);
    return groups;
  },
  {}
);

const token = localStorage.getItem("token");
const decoded = jwtDecode(token);
const role = decoded["http://schemas.microsoft.com/ws/2008/06/identity/claims/role"];
const isAdminView = role === "Admin" && window.location.search.includes("admin=true");

const totalSpent = trip.activities.reduce((sum, activity) =>sum + activity.estimatedCost, 0);
const remainingBudget = trip.budget - totalSpent;

  return (
    <div className="app">
      <div className="top-strip">
          
          <button
            className="back-btn"
            onClick={() => navigate("/dashboard")}>
            ← Back to Dashboard
          </button>
      
          {!isAdminView && (
            <>
              <div className="share-top-wrapper">

                <select
                  value={shareAccess}
                  onChange={(e) =>
                    setShareAccess(e.target.value)}>
                  <option value="VIEW">
                    VIEW
                  </option>

                  <option value="EDIT">
                    EDIT
                  </option>
                </select>

                <button
                  className="share-top-btn"
                  onClick={createShareLink}>
                  📱 Share
                </button>

                  <button className="pdf-btn" onClick={generatePdf}>
                    📄 Download PDF
                  </button>

              </div>
              {shareLink && (
                <div className="top-qr-wrapper">

                  <QRCodeCanvas
                    value={shareLink}
                    size={120} />

                  <div className="generated-link">
                    <span>
                      {shareLink}
                    </span>

                    <span
                      className="copy-icon"
                      onClick={copyShareLink}>
                      📋
                    </span>

                  </div>

                  <button
                    className="cancel-qr-btn"
                    onClick={() => setShareLink("")}>
                    ✕
                  </button>
           
                </div>
              )}
            </>
          )}

        
          <div className="top-strip-right">

            
          <div className="top-strip-user">
            👤 {decoded ["http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"] }
             • {role}
          </div>
        </div>

          <button
            className="logout-btn"
            onClick={() => {
              localStorage.removeItem(
                "token"
              );
              navigate("/");}}>
            Logout
          </button>
        </div>

      <div className="container">
        <h1 className="title">✈️ {trip.title}</h1>
          

        <div className="overview-section">
          <div className="trip-card trip-summary">
          
            <p>{trip.description}</p>

            📅 {
              new Date(
                trip.startDate
              ).toLocaleDateString(
                "en-US",
                {
                  day: "numeric",
                  month: "short",           
                }
              )
            }

            {" —  "}

            {
              new Date(
                trip.endDate
              ).toLocaleDateString(
                "en-US",
                {
                  day: "numeric",
                  month: "short",                
                }
              )
            }

            {budgetSummary && (
              <div className="budget-summary">
                <div className="remaining-budget">
                  🏖️ {budgetSummary.remaining}
                  <span>
                    left to spend
                  </span>
                </div>

                <div className="budget-pill">
                  💳 Budget:
                  {" "}
                  {budgetSummary.plannedBudget}
                </div>

                <div className="budget-pill">
                  💵 Spent:
                  {" "}
                  {budgetSummary.spent}
                </div>
              </div>
            )}
 
      </div>
         
        <div className="trip-card checklist-container notes-container">
          <h2 className="checklist-title"> Reminder </h2>
          {checklist.map((item) => (
            <label
              key={item.id}
              className="checklist-item">              
              <input
                type="checkbox"
                checked={item.completed}
                disabled={isAdminView}
                onChange={() =>
                  toggleChecklistItem(item.id)}/>
              <span>{item.text}</span>
            </label> 
          ))}

          {!isAdminView && (
            <div className="mini-add-wrapper">
              {!showReminderInput ? (

                <button
                  className="mini-add-btn"
                  onClick={() =>
                    setShowReminderInput(true)
                  }
                >
                  +
                </button>

                  ) : (

                    <>
                      <input
                        type="text"
                        placeholder="New reminder"
                        value={checklistItem}
                        onChange={(e) =>setChecklistItem(e.target.value)}
                        className="mini-note-input"/>

                  <button
                    className="mini-add-btn"
                    onClick={() => {addChecklistItem();
                    setShowReminderInput(
                    false
                  );
                }}
              >
                ✓
              </button>
            </>
          )}

        </div>
      )}
        </div>

        <div className="trip-card notes-container">
          <h2 className="checklist-title"> Activity Notes</h2>
          {trip.activities.filter((a) => a.notes).map((activity) => (
            <div key={activity.id} className="note-item">
              <p><strong>{activity.title}</strong> : {activity.notes}</p>
            </div>
          ))}
        </div>
          <CalendarView activities={trip.activities}/>
      </div>
    
        <h2 className="section-title">Destinations</h2>
        <div className="trip-grid">
          {trip.destinations.map((destination) => (
            <div key={destination.id} className="trip-card destination-card">
              <h3><span className="emoji">📍</span> {destination.name}</h3>

              <p>{destination.location}</p>
              <p>{destination.description}</p>
              <p className="date-text">
                  📅 {destination.arrivalDate.slice(0, 10)} →{" "}
                  {destination.departureDate.slice(0, 10)}
              </p>

              <div className="card-buttons">
                {!isAdminView && (
                  <button
                    className="edit-btn"
                    onClick={() => navigate( isAdminView
                      ?`/trip/${trip.id}/destination/${destination.id}`
                      : `/trip/${trip.id}/destination/${destination.id}`
                    )}>
                      Edit
                  </button>
                )}
                
                <button
                  className="delete-btn"
                  onClick={() => deleteDestination(destination.id)}>
                    Delete
                </button>

              </div>  
            </div>         
          ))}
          
          
        </div>

        {!isAdminView && (
          <button
            className="add-card"
            onClick={() => navigate(`/trip/${trip.id}/destination`)}>
            + Add Destination
          </button>
        )}

        <div className="activities-section">   
          <h2 className="section-title">Activities</h2>
          {Object.entries(groupActivities).map(([date, activities]) => (
          <div key={date} >
            <h3 className="activity-date-heading">🗓️ {
                new Date(date).toLocaleDateString("en-US",{ weekday: "long" })
                } • {date}</h3>

            <div className="activities-grid">{activities.sort((a, b) =>
              a.time.localeCompare(b.time)).map((activity) => (
              <div key={activity.id}className="trip-card activity-card">
                
                <h3>{activity.title}</h3>
                <p className="date-text">🕒 {activity.time}</p>
                <p>{activity.location}</p>
                <p>{activity.description}</p>
                <p>Cost: {activity.estimatedCost} {" → "} {activity.category}</p>
                <p>📌 {activity.status}</p>
                <p>📝 {activity.notes}</p>
                
                
                <div className="card-buttons">
                  {!isAdminView && (
                  <button className="edit-btn"
                    onClick={() => navigate( isAdminView ? `trip/${trip.id}/activity/${activity.id}?admin=true`
                                                         : `/trip/${trip.id}/activity/${activity.id}`)}>
                    Edit
                  </button>
                  )}                  
                  <button className="delete-btn"
                    onClick={() => deleteActivity(activity.id)}>
                    Delete
                  </button>                 
                  </div>
                </div>
                ))}
              
                </div>
              </div>
            ))}
          </div> 

          {!isAdminView && (
            <button
              className="add-card"
              onClick={() => navigate(`/trip/${trip.id}/activity`)}>
              + Add Activity
            </button>
          )}

        </div>
    </div>
  );
}

export default TripDetailsPage;